### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rikardg** [rikardg/bygg#12]
This issue will be updated as the project moves forward, and issues spawned off when it's time to work on them.

- [ ] Visualisation: some form of graph output, either in the program itself or via something like tikz.
- [ ] Performance analysis/report: how long time each job took, possibly with some form for aggregation.
- [ ] More documentation: today, one has to read the examples to understand how to use Bygg. There should exist a brief user guide and documentation of the (thin) API surface.
